//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagerSite.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<ClientProfiles> ClientProfiles { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Project_Projects> Project_Projects { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<Projects_Skills> Projects_Skills { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<Teams_Projects> Teams_Projects { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Users_Projects> Users_Projects { get; set; }
        public virtual DbSet<Users_Skills> Users_Skills { get; set; }
        public virtual DbSet<Users_Teams> Users_Teams { get; set; }
    }
}
